### ISSUE TITLE
"Well that didn't work..." message after the upgrade

### ISSUE THREAD

**Issue by antoinekh** [vances678/ContainerBookmarks#2]
hello,

This the upgrade I have a new issue:
![image](https://user-images.githubusercontent.com/52744345/138428639-0a31ff2f-8e59-4810-9078-40ee0c15a407.png)

URL: moz-extension://48c986af-cad8-47b5-b21e-45f4102721d3/handler.html#ext%2Bcntnrbkmrk%3Acontainer%3DHome%26url%3Dhttps%3A%2F%2Fweb.telegram.org%2F%23%2Fim

The website works well in the container

**Comment by vances678** [comment]
Sorry about that - I seem to have uploaded a file that I was using for testing instead of the real file in the last version. I just uploaded version 1.4.2 with the correct files, and I have verified that the extension functions properly on that version.

Apologies for the inconvenience,
-Vance
